config/routes.rb
TwilioIs::Application.routes.draw do
  
  root :to => 'sms#index'
  
  match '/receive-sms', to: 'sms#receive_text_message'
  match '/send_sms', to: 'sms#send_text_message'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sms_controller.rb
class SmsController < ApplicationController
  
  def send_text_message
    number_to_send_to = params[:number_to_send_to]

    twilio_sid = "ACe540ea3ae4f7620548712b8838abe3c9"
    twilio_token = "7668eade2e87d2d78f3bc948a610e66e"
    twilio_phone_number = "17039977790"

    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token

    @twilio_client.account.sms.messages.create(
      :from => "+1#{twilio_phone_number}",
      :to => number_to_send_to,
      :body => "This is an message. It gets sent to #{number_to_send_to}"
    )
    
   redirect_to root_url
  end
  
  def receive_text_message 
    # let's pretend that we've mapped this action to 
    # http://localhost:3000/sms in the routes.rb file
    
    message_body = params["Body"]
    from_number = params["From"]

    SMSLogger.log_text_message from_number, message_body
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sms_helper.rb
module SmsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwilioIs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sms/index.html.erb
<h1>Send a Text</h1>

 <div class="row">
  <div class="span6 offset3">
    <%= form_tag send_sms_path do %>

<%= label_tag :number_to_send_to %>

      <%= text_field_tag :number_to_send_to, params[:number_to_send_to] %>
 

      <%= submit_tag "Send Text", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>